# Generated by Django 4.0.4 on 2022-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_userimage_user_userimage_user_image_users_bio_and_more'),
        ('shop', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.conditions'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myprofile.users'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='imgURL',
            field=models.CharField(default=None, max_length=9999),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
        migrations.AddField(
            model_name='offers',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='offers',
            name='amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='offers',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myprofile.users'),
        ),
        migrations.AddField(
            model_name='offers',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
