# Generated by Django 4.0.4 on 2022-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_conditions_status_item_available_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceidea',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='offers',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
