# Generated by Django 4.0.4 on 2022-05-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_available'),
        ('shop', '0005_alter_item_available_alter_item_seller_and_more'),
    ]

    operations = [
    ]
