# Generated by Django 4.0.4 on 2022-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20220508_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='outbid',
            field=models.BooleanField(default=False),
        ),
    ]
