# Generated by Django 4.0.4 on 2022-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_offers_outbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='heighestoffer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
