# Generated by Django 4.0.4 on 2022-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_heighestoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
