# Generated by Django 4.0.4 on 2022-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_offers_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='imgURL',
            field=models.CharField(default=None, max_length=50000),
        ),
    ]
