# Generated by Django 4.0.4 on 2022-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_conditions_status_item_available_item_condition_and_more'),
        ('myprofile', '0003_userimage_user_userimage_user_image_users_bio_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='offerID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.offers'),
        ),
        migrations.AddField(
            model_name='order',
            name='payID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.payments'),
        ),
        migrations.AddField(
            model_name='payments',
            name='CVC',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='payments',
            name='card_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='card_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='payments',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='companyname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='checkout.country'),
        ),
        migrations.AddField(
            model_name='payments',
            name='exdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='payments',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='payments',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='userID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myprofile.users'),
        ),
        migrations.AddField(
            model_name='payments',
            name='zip',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stars',
            name='star_img',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AddField(
            model_name='stars',
            name='star_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stars',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myprofile.users'),
        ),
    ]
