# Generated by Django 4.0.4 on 2022-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_payments_userid_alter_stars_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='companyname',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
