# Generated by Django 4.0.4 on 2022-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_payments_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_num',
            field=models.BigIntegerField(default=None),
        ),
    ]
