# Generated by Django 4.0.4 on 2022-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_payments_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
