# Generated by Django 4.0.4 on 2022-05-11 14:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_reviews_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
