# Generated by Django 4.0.4 on 2022-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_payments_country_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='CVC',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
