# Generated by Django 4.0.4 on 2022-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_payments_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_num',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
