# Generated by Django 4.0.4 on 2022-05-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_itemimage_imgurl'),
        ('checkout', '0013_alter_payments_card_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='order',
        ),
        migrations.AddField(
            model_name='reviews',
            name='offer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.offers'),
        ),
    ]
