# Generated by Django 4.0.4 on 2022-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_payments_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='housenumber',
            field=models.IntegerField(default=None),
        ),
    ]
