# Generated by Django 4.0.4 on 2022-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_delete_offers_delete_order_delete_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myprofile.users'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user_image',
            field=models.CharField(default=None, max_length=9999),
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
