# Generated by Django 4.0.4 on 2022-05-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_alter_userimage_user'),
        ('myprofile', '0004_remove_users_email_remove_users_name_and_more'),
    ]

    operations = [
    ]
