# Generated by Django 4.0.4 on 2022-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_merge_20220508_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fullname',
            field=models.CharField(default='', max_length=300),
        ),
    ]
