# Generated by Django 4.0.4 on 2022-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_alter_users_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_image',
            field=models.CharField(default=None, max_length=50000),
        ),
    ]
